### ISSUE TITLE
popper-class

### ISSUE THREAD

**Issue by mzx123** [hyjiacan/vue-datepicker#1]
我在popper-class属性传入了个自己写的class
z-index: 2147483647;
但是弹出框还是会被其他控件遮挡，这可能是什么原因

**Comment by hyjiacan** [comment]
看看样式有没有应用上。注意指定的 `popper-class` 不能是组件内的样式，需要为全局样式才能生效。

**Comment by hyjiacan** [comment]
已经过了这么久，不知道问题有没有解决，要是没问题了，就关闭了
